name: Dist CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:


defaults:
  run:
    shell: bash

jobs:
  dist-ci:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - name: Run CI script
        run: .ci/script.sh
      - name: Apple Silicon Build
        if: matrix.os == 'macos-latest'
        run: |
          sudo rm -Rf /Library/Developer/CommandLineTools/SDKs/*
          sudo xcode-select -s /Applications/Xcode_12.4.app
          CROSS_CI="aarch64-apple-darwin" .ci/script.sh
      - name: iOS aarch64
        if: matrix.os == 'macos-latest'
        run: |
          sudo rm -Rf /Library/Developer/CommandLineTools/SDKs/*
          sudo xcode-select -s /Applications/Xcode_12.4.app
          CROSS_CI="aarch64-apple-ios" .ci/script.sh
      - name: iOS x64 simulator
        if: matrix.os == 'macos-latest'
        run: |
          sudo rm -Rf /Library/Developer/CommandLineTools/SDKs/*
          sudo xcode-select -s /Applications/Xcode_12.4.app
          CROSS_CI="x86_64-apple-ios-simulator" .ci/script.sh
